### ISSUE TITLE
500 error when I try to deploy a non-upgradable contract with a linked library and CREATE2 salt

### ISSUE THREAD

**Issue by cedoor** [OpenZeppelin/openzeppelin-upgrades#959]
I'm using the `defender.deployContract` function to deploy (deterministically) a contract ([Semaphore.sol](https://github.com/semaphore-protocol/semaphore/blob/chore/oz-deployer/packages/contracts/contracts/Semaphore.sol)) where its constructor parameter is a simple address and it also needs a linked library ([PoseidonT3](https://github.com/vimwitch/poseidon-solidity/blob/main/contracts/PoseidonT3.sol)).

```ts
const SemaphoreFactory = await ethers.getContractFactory("Semaphore", {
  libraries: {
      PoseidonT3: poseidonAddress
  }
})

const semaphore = await defender.deployContract(SemaphoreFactory, [verifierAddress], {
    salt: process.env.CREATE2_SALT,
    unsafeAllow: ["external-library-linking", "constructor"],
    unsafeAllowDeployContract: true
})

await semaphore.waitForDeployment()
```

Ref: https://github.com/semaphore-protocol/semaphore/blob/f0be86671278f6ab610ac36da9196b8d74d757c6/packages/contracts/tasks/deploy-semaphore.ts#L62-L66.

I've also tried to use some unsafeAllow options but I get the same error:

DefenderApiResponseError: Request failed with status code 500.
```js
{
  request: { path: '/v2/deployments', method: 'POST' },
  response: {
      status: 500,
      statusText: 'Internal Server Error',
      data: {
        message: 'invalid arrayify value (argument="value", value="0x60806040523480156200001157600080fd5b50... ~17k more characters',
        ...
      }
  }
}
```

I have no problems with the other contracts, which have no constructors or linked libraries (e.g. [SemaphoreVerifier.sol](https://github.com/semaphore-protocol/semaphore/blob/chore/oz-deployer/packages/contracts/contracts/base/SemaphoreVerifier.sol)).

**Comment by ericglau** [comment]
Hi @cedoor, thanks for reporting this. We've identified an internal Defender error that occurs in this scenario and are working on a fix. I'll let you know when the fix is available.

**Comment by cedoor** [comment]
> Hi @cedoor, thanks for reporting this. We've identified an internal Defender error that occurs in this scenario and are working on a fix. I'll let you know when the fix is available.

Hi @ericglau, thank you very much!

**Comment by ericglau** [comment]
Hi @cedoor , this is fixed in `@openzeppelin/hardhat-upgrades@3.0.4`

**Comment by cedoor** [comment]
@ericglau thank you very much 🙏🏽 We'll update our dependency asap and test it!

**Comment by cedoor** [comment]
Hi @ericglau, I still see a 500 error:
```
response: {
    status: 500,
    statusText: 'Internal Server Error',
    data: {
      message: 'User: arn:aws:sts::665768922667:assumed-role/defender-api-external-api-sts-lambda-assume-role/303216d1-fa7d-4fca-8c5b-7ba1ba544fc7 is not authorized to perform: kms:Sign on resource: arn:aws:kms:us-west-2:665768922667:key/67fd5980-6e70-4d0d-af2f-cc1aff31aa9a because no session policy allows the kms:Sign action'
    }
  }
```

I wonder if I need to update something.

**Comment by ericglau** [comment]
Thanks @cedoor, I see the same error as well. We are looking into this issue.

**Comment by dylankilkenny** [comment]
@cedoor Can you share your `tenantId` with me please (you can find this in the hamburger menu in the top right). Also you might be able to unblock yourself by creating a new approval process with the same relayer and adding it to your deployment config

**Comment by cedoor** [comment]
> @cedoor Can you share your `tenantId` with me please (you can find this in the hamburger menu in the top right). Also you might be able to unblock yourself by creating a new approval process with the same relayer and adding it to your deployment config

Sure, `303216d1-fa7d-4fca-8c5b-7ba1ba544fc7`. I'll try to create a new approval process.

**Comment by cedoor** [comment]
@dylankilkenny it works now :) Thanks!

**Comment by alysiahuggins** [comment]
I get the error error as the original poster when using the DefenderAPI with Foundry. I have also linked an external library and added `/// @custom:oz-upgrades-unsafe-allow external-library-linking` at the top of the smart contract to be deployed.

**Comment by ericglau** [comment]
Thanks for raising this. I've opened https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/26 to address this in Foundry, please subscribe to that issue for updates.
